name: async_status
description: "An async status (aka async value) for handling asynchronous states with futures and streams. States: data, error, loading, reloading"
version: 0.1.0
repository: https://github.com/mcmah309/async_status

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
